import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowUp, Atom, BookOpen, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, FileText, FlaskConical, ImagePlus, LogOut, Menu, Moon, Plus, Search, Sparkles, Sun, Trash2, Upload, X } from 'lucide-react';
import Papa from 'papaparse';
import { api, articlesApi } from './api';
import { uploadHeroImage } from './mediaUpload';

const fmt = date => date ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date)) : '—';
const slugify = value => value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const unwrap = d => Array.isArray(d) ? d : d?.articles || d?.items || d?.categories || [];

function Login({ onLogin }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const d = await articlesApi.login({ email, password }); const token = d?.accessToken || d?.token || d?.user?.accessToken; if (!token) throw new Error('The server did not return an access token.'); sessionStorage.setItem('chemsiq_admin_token', token); if (d?.refreshToken) sessionStorage.setItem('chemsiq_admin_refresh_token', d.refreshToken); onLogin(); } catch (e) { setError(e.response?.data?.error?.message || e.message || 'Could not sign in.'); } finally { setBusy(false); } }
  return <main className="login-page"><div className="login-card"><Brand/><div className="eyebrow">CONTENT WORKSPACE</div><h1>Welcome back</h1><p>Sign in to manage Chemsiq articles.</p><form onSubmit={submit}><label>Email address<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@chemsiq.app"/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/></label>{error&&<div className="error-box">{error}</div>}<button className="primary wide" disabled={busy}>{busy?<span className="spinner"/>:'Sign in'}<ChevronRight size={17}/></button></form><small>Admin access only · Your session stays in this tab</small></div></main>
}
function Brand(){return <div className="brand"><div className="brand-icon"><Atom size={21}/></div><div><strong>chemsiq</strong><small>STUDIO</small></div></div>}

function Editor({ initial, categories, topics, onClose, onSaved }) {
  const [form,setForm]=useState(()=>initial?{...initial, category:initial.category?._id||initial.category||'', topics:(initial.topics||[]).map(x=>x._id||x), author:initial.author||{name:'',bio:'',avatarUrl:''},heroImage:initial.heroImage||{url:'',caption:''}}:{title:'',slug:'',category:'',topics:[],excerpt:'',content:'',author:{name:'',bio:'',avatarUrl:''},heroImage:{url:'',caption:''},status:'draft',featured:false});
  const [busy,setBusy]=useState(false),[err,setErr]=useState(''),[imgBusy,setImgBusy]=useState(false),[imgProgress,setImgProgress]=useState(0),[dragging,setDragging]=useState(false),[tagInput,setTagInput]=useState(''); const picker=useRef();
  const set=(k,v)=>setForm(f=>({...f,[k]:v})); const setAuthor=(k,v)=>setForm(f=>({...f,author:{...f.author,[k]:v}})); const setImage=(k,v)=>setForm(f=>({...f,heroImage:{...f.heroImage,[k]:v}}));
  const words=(form.content||'').trim().split(/\s+/).filter(Boolean).length;
  async function save(e){e.preventDefault();if(imgBusy){setErr('Wait for the hero image to finish uploading.');return}setBusy(true);setErr('');try{const body={...form,readTimeMinutes:Math.max(1,Math.ceil(words/220))};initial?await articlesApi.update(initial._id||initial.id,body):await articlesApi.create(body);onSaved();}catch(e){setErr(e.response?.data?.error?.message||e.message||'Could not save article.');}finally{setBusy(false)}}
  async function imageChange(file){if(!file)return;setImgBusy(true);setImgProgress(0);setErr('');try{const result=await uploadHeroImage(file,{onProgress:setImgProgress});setImage('url',result.url);setImage('publicId',result.publicId)}catch(e){setErr(e.message)}finally{setImgBusy(false);setImgProgress(0);if(picker.current)picker.current.value=''}}
  function addTag(){const t=tagInput.trim();if(!t)return;if(form.topics.length>=5){setErr('You can add up to five topics.');return}const found=topics.find(x=>(x.name||'').toLowerCase()===t.toLowerCase());if(found){const id=found._id||found.id;if(!form.topics.includes(id))set('topics',[...form.topics,id]);setErr('')}else setErr(`“${t}” is not in the topics list yet.`);setTagInput('')}
  return <div className="overlay"><section className="editor-sheet"><header className="editor-top"><button className="icon-btn" onClick={onClose}><X size={18}/></button><div><div className="eyebrow">{initial?'EDIT ARTICLE':'NEW ARTICLE'}</div><strong>{initial?'Update your story':'Create a story'}</strong></div><span className="grow"/><button className="secondary" onClick={()=>{set('status','draft');setTimeout(()=>document.getElementById('editor-form')?.requestSubmit(),0)}}>Save draft</button><button className="primary" onClick={()=>{set('status','published');setTimeout(()=>document.getElementById('editor-form')?.requestSubmit(),0)}} disabled={busy}>{busy?<span className="spinner"/>:<>{form.status==='published'?'Update article':'Publish article'} <ArrowUp size={15}/></>}</button></header>
  <form id="editor-form" className="editor-scroll" onSubmit={save}><div className="editor-main"><div className="editor-title"><input value={form.title} onChange={e=>{set('title',e.target.value);set('slug',slugify(e.target.value))}} placeholder="Give your article a clear, compelling title" maxLength="200" required/><div className="slug-preview">chemsiq.app/articles/<b>{form.slug||'your-article-slug'}</b></div></div>
  <div className="field-grid"><label>Category<select required value={form.category} onChange={e=>set('category',e.target.value)}><option value="">Select a category</option>{categories.map(c=><option key={c._id||c.id} value={c._id||c.id}>{c.name}</option>)}</select></label><label>Author name<input required value={form.author.name||''} onChange={e=>setAuthor('name',e.target.value)} placeholder="Author name"/></label></div>
  <label>Summary <span className="hint">{(form.excerpt||'').length}/500</span><textarea required maxLength="500" rows="3" value={form.excerpt||''} onChange={e=>set('excerpt',e.target.value)} placeholder="A short introduction to your article…"/></label>
  <label>Topics <span className="hint">{form.topics.length}/5</span><div className="chips">{form.topics.map(id=>{const t=topics.find(x=>(x._id||x.id)===id);return <button className="chip" type="button" key={id} onClick={()=>set('topics',form.topics.filter(x=>x!==id))}>{t?.name||id}<X size={12}/></button>})}<div className="chip-entry"><input disabled={form.topics.length>=5} value={tagInput} onChange={e=>setTagInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTag()}}} placeholder={form.topics.length?'Add a topic…':'Search topics…'}/><button type="button" onClick={addTag} aria-label="Add topic"><Plus size={14}/></button></div></div></label>
  <label>Article content <span className="hint">Markdown supported · {words} words · ~{Math.max(1,Math.ceil(words/220))} min read</span><textarea className="content-editor" required value={form.content||''} onChange={e=>set('content',e.target.value)} placeholder={'## Start writing…\n\nUse Markdown for headings, lists, quotes, and code. Chemistry notation like H₂O or $\\ce{H2O}$ works.'}/></label>
  <div className="field-grid"><label>Author bio<input value={form.author.bio||''} onChange={e=>setAuthor('bio',e.target.value)} placeholder="A little about the author"/></label><label>Author avatar URL<input type="url" value={form.author.avatarUrl||''} onChange={e=>setAuthor('avatarUrl',e.target.value)} placeholder="https://…"/></label></div>
  <label>Hero image <span className="hint">JPEG, PNG or WebP · max 5 MB</span><div className={`upload-row ${dragging?'dragging':''}`} role="button" tabIndex={0} onClick={e=>{e.preventDefault();e.stopPropagation();picker.current?.click()}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();picker.current?.click()}}} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);imageChange(e.dataTransfer.files?.[0])}}>{form.heroImage.url?<img src={form.heroImage.url} className="hero-preview" alt="Hero preview"/>:<div className="upload-icon"><ImagePlus/></div>}<div><b>{imgBusy?`Uploading image… ${imgProgress}%`:form.heroImage.url?'Image ready · change image':'Drop an image here or browse'}</b><small>{imgBusy?'Keep this editor open while the image uploads.':'Your image uploads as soon as you choose it.'}</small>{imgBusy&&<div className="image-progress"><span style={{width:`${imgProgress}%`}}/></div>}</div><Upload size={17}/><input ref={picker} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>imageChange(e.target.files?.[0])}/></div></label>{form.heroImage.url&&<label>Image caption<input value={form.heroImage.caption||''} onChange={e=>setImage('caption',e.target.value)} placeholder="Describe the image"/></label>}
  {err&&<div className="error-box">{err}</div>}</div><aside className="editor-aside"><div className="card side-card"><div className="eyebrow">PUBLISHING</div><div className="status-control"><span className={`dot ${form.status}`}/><div><b>{form.status==='published'?'Published':'Draft'}</b><small>{form.status==='published'?'Visible to your readers':'Only visible to your team'}</small></div><button type="button" className="switch" aria-label="Toggle status" onClick={()=>set('status',form.status==='draft'?'published':'draft')}><span/></button></div><hr/><div className="toggle-row"><div><b>Featured article</b><small>Show in featured stories</small></div><button type="button" className={`switch ${form.featured?'on':''}`} onClick={()=>set('featured',!form.featured)}><span/></button></div></div><div className="card side-card"><Sparkles size={18} className="teal"/><h3>A note on chemistry</h3><p>Keep notation clear and accessible. Use subscripts such as H₂O in plain text or add LaTeX style formula notation in the body.</p></div></aside></form></section></div>
}

function Bulk({onClose,onDone,categories,topics}){const [rows,setRows]=useState([]),[errors,setErrors]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[report,setReport]=useState(null);const file=useRef();
  function parse(f){setReport(null);setErrors([]);if(!f)return;const done=records=>{const categoryNames=new Set(categories.map(c=>(c.name||'').toLowerCase())),topicNames=new Set(topics.map(t=>(t.name||'').toLowerCase()));const problems=[];records.forEach((r,i)=>{if(!r.title?.trim())problems.push(`Row ${i+1}: title is required`);if(!r.category?.trim())problems.push(`Row ${i+1}: category is required`);else if(categoryNames.size&&!categoryNames.has(r.category.toLowerCase()))problems.push(`Row ${i+1}: unknown category “${r.category}”`);if(!r.content?.trim())problems.push(`Row ${i+1}: content is required`);if((r.excerpt||'').length>500)problems.push(`Row ${i+1}: excerpt exceeds 500 characters`);if(r.topics&&topicNames.size)r.topics.split('|').forEach(t=>{if(!topicNames.has(t.trim().toLowerCase()))problems.push(`Row ${i+1}: unknown topic “${t.trim()}”`)})});setRows(records);setErrors(problems)};
  if(f.name.endsWith('.json')){const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);done(Array.isArray(d)?d:d.articles)}catch{setErrors(['Invalid JSON file.'])}};reader.readAsText(f)}else Papa.parse(f,{header:true,skipEmptyLines:true,complete:r=>done(r.data),error:()=>setErrors(['Could not parse CSV file.'])})}
  async function importRows(){setBusy(true);setProgress(10);try{const normalized=rows.map(r=>({title:r.title,category:categories.find(c=>c.name.toLowerCase()===r.category.toLowerCase())?._id,excerpt:r.excerpt||'',content:r.content,author:{name:r.author||'Chemsiq Editorial'},topics:(r.topics||'').split('|').filter(Boolean).map(n=>topics.find(t=>t.name.toLowerCase()===n.trim().toLowerCase())?._id).filter(Boolean),status:r.status==='published'?'published':'draft',featured:r.featured==='true'}));const out=await articlesApi.bulk({articles:normalized});setProgress(100);setReport(out);onDone()}catch(e){setErrors([e.response?.data?.error?.message||e.message||'Import failed.'])}finally{setBusy(false)}}
  return <div className="overlay"><section className="modal"><header><div><div className="eyebrow">BULK IMPORT</div><h2>Bring in your articles</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header><p className="muted">Upload a JSON or CSV file. We’ll validate every row before sending it to your workspace.</p>{!rows.length?<button className="file-drop" onClick={()=>file.current?.click()}><div className="upload-icon"><Upload/></div><b>Choose a file to upload</b><span>JSON or CSV · one article per row</span><input ref={file} hidden type="file" accept=".json,.csv,application/json,text/csv" onChange={e=>parse(e.target.files?.[0])}/></button>:<><div className="file-selected"><FileText/><div><b>{rows.length} articles ready</b><small>Parsed and checked in your browser</small></div><button className="text-button" onClick={()=>{setRows([]);setErrors([])}}>Replace file</button></div><div className="schema-note"><b>CSV columns:</b> title, category, content, excerpt, author, topics (use | between topics), status, featured. JSON accepts the same fields.</div></>}{errors.length>0&&<div className="validation-errors">{errors.slice(0,6).map((e,i)=><div key={i}>• {e}</div>)}{errors.length>6&&<small>and {errors.length-6} more issues</small>}</div>}{report&&<div className="success-box">Import complete · {report.created?.length??report.successCount??0} created · {report.failed?.length??report.failureCount??0} failed</div>}{busy&&<div className="progress"><div style={{width:`${progress}%`}}/></div>}<footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!rows.length||!!errors.length||busy} onClick={importRows}>{busy?<span className="spinner"/>:<><Upload size={16}/> Import {rows.length||''} articles</>}</button></footer></section></div>
}

export default function App(){const [token,setToken]=useState(()=>sessionStorage.getItem('chemsiq_admin_token'));const [dark,setDark]=useState(()=>localStorage.getItem('chemsiq_theme')!=='light');const [menuOpen,setMenuOpen]=useState(false);const searchRef=useRef(null);const [articles,setArticles]=useState([]),[categories,setCategories]=useState([]),[topics,setTopics]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All categories'),[status,setStatus]=useState('All status'),[editor,setEditor]=useState(null),[showBulk,setShowBulk]=useState(false),[deleteItem,setDeleteItem]=useState(null),[notice,setNotice]=useState('');
  useEffect(()=>{const f=()=>setToken(null);window.addEventListener('admin:unauthorized',f);return()=>window.removeEventListener('admin:unauthorized',f)},[]);
  useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('chemsiq_theme',dark?'dark':'light')},[dark]);
  useEffect(()=>{const shortcut=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus()}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[]);
  async function load(){setLoading(true);setErr('');try{const [a,c,t]=await Promise.all([articlesApi.list({limit:100}),articlesApi.categories().catch(()=>[]),articlesApi.topics().catch(()=>[])]);setArticles(unwrap(a));setCategories(unwrap(c));setTopics(unwrap(t))}catch(e){setErr(e.response?.data?.error?.message||e.message||'Could not load articles.')}finally{setLoading(false)}}
  useEffect(()=>{if(token)load()},[token]);
  const filtered=useMemo(()=>articles.filter(a=>(!search||`${a.title} ${a.author?.name} ${a.slug}`.toLowerCase().includes(search.toLowerCase()))&&(category==='All categories'||(a.category?.name||a.category)===category)&&(status==='All status'||a.status===status.toLowerCase())),[articles,search,category,status]);
  async function toggle(a){try{await articlesApi.update(a._id||a.id,{status:a.status==='published'?'draft':'published'});setNotice(`Article moved to ${a.status==='published'?'drafts':'published'}.`);load()}catch(e){setErr(e.response?.data?.error?.message||'Could not update article.')}}
  async function remove(){try{await articlesApi.remove(deleteItem._id||deleteItem.id);setDeleteItem(null);setNotice('Article deleted.');load()}catch(e){setErr(e.response?.data?.error?.message||'Could not delete article.')}}
  if(!token)return <Login onLogin={()=>setToken(sessionStorage.getItem('chemsiq_admin_token'))}/>;
  const published=articles.filter(a=>a.status==='published').length, drafts=articles.filter(a=>a.status!=='published').length;
  return <div className="app-shell">{menuOpen&&<button className="mobile-backdrop" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}<aside className={`sidebar ${menuOpen?'open':''}`}><Brand/><div className="workspace"><div className="workspace-avatar">C</div><div><b>Chemsiq</b><small>Editorial workspace</small></div></div><div className="nav-label">CONTENT</div><button className="nav-item active" onClick={()=>setMenuOpen(false)}><BookOpen size={17}/> Articles <span>{articles.length}</span></button><button className="nav-item" onClick={()=>{setShowBulk(true);setMenuOpen(false)}}><Upload size={17}/> Import articles</button><div className="sidebar-bottom"><div className="help-card"><CircleHelp size={18}/><b>Quick tip</b><p>Use <kbd>Ctrl K</kbd> to search, or import a batch of articles from JSON or CSV.</p><button className="quick-create" onClick={()=>{setEditor({});setMenuOpen(false)}}><Plus size={13}/> Write an article</button></div><div className="user-card"><div className="user-avatar">E</div><div><b>Editorial team</b><small>Administrator</small></div></div></div></aside>
  <main className="main"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu/></button><div className="crumb">Workspace <ChevronRight size={14}/> <b>Articles</b></div><span className="grow"/><button className="icon-btn" title={dark?'Switch to light theme':'Switch to dark theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-btn" title="Sign out" onClick={()=>{sessionStorage.removeItem('chemsiq_admin_token');sessionStorage.removeItem('chemsiq_admin_refresh_token');setToken(null)}}><LogOut size={17}/></button><div className="user-avatar tiny">E</div></header>
  <div className="page"><div className="page-heading"><div><div className="eyebrow">YOUR CONTENT, IN ONE PLACE</div><h1>Articles <span className="count-pill">{articles.length}</span></h1><p>Write, organize, and publish stories for the Chemsiq community.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>setShowBulk(true)}><Upload size={16}/> Bulk upload</button><button className="primary" onClick={()=>setEditor({})}><Plus size={17}/> New article</button></div></div>
  <div className="stats-grid"><Stat icon={<FileText/>} label="Total articles" value={articles.length} note="Across your workspace" tone="blue"/><Stat icon={<Activity/>} label="Published" value={published} note="Live for your readers" tone="green"/><Stat icon={<Clock3/>} label="Drafts" value={drafts} note="Work in progress" tone="amber"/><Stat icon={<FlaskConical/>} label="Categories" value={categories.length} note="Topics of discovery" tone="violet"/></div>
  <section className="card table-card"><div className="table-heading"><div><h2>All articles</h2><p>Manage and track your published content</p></div></div><div className="table-tools"><div className="searchbox"><Search size={16}/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title or author…"/><kbd>Ctrl K</kbd></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All categories</option>{categories.map(c=><option key={c._id||c.id}>{c.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All status</option><option>Published</option><option>Draft</option></select><button className="secondary compact" onClick={()=>setShowBulk(true)}><Upload size={15}/> Import articles</button></div>
  {err&&<div className="error-box table-error">{err}<button onClick={()=>setErr('')}><X size={14}/></button></div>}
  <div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all"/></th><th>ARTICLE</th><th>CATEGORY</th><th>AUTHOR</th><th>STATUS</th><th>LAST UPDATED</th><th/></tr></thead><tbody>{loading?<tr><td colSpan="7"><div className="loading-state"><span className="spinner dark-spinner"/> Loading articles…</div></td></tr>:filtered.length===0?<tr><td colSpan="7"><div className="empty-state"><div className="empty-icon"><BookOpen/></div><b>{articles.length?'No articles match your filters':'Your story starts here'}</b><p>{articles.length?'Try adjusting your search or filters.':'Create your first article and share something curious.'}</p>{!articles.length&&<button className="primary" onClick={()=>setEditor({})}><Plus size={16}/> Create article</button>}</div></td></tr>:filtered.map((a,i)=><tr key={a._id||a.id||i}><td><input type="checkbox" aria-label={`Select ${a.title}`}/></td><td><div className="article-cell">{a.heroImage?.url?<img src={a.heroImage.url} alt=""/>:<div className="thumb-placeholder"><Atom size={18}/></div>}<div><b>{a.title}</b><small>/articles/{a.slug||slugify(a.title||'')}</small></div></div></td><td><span className="category-pill">{a.category?.name||a.category||'Uncategorized'}</span>{a.topics?.length>0&&<small className="topic-sub">{a.topics.slice(0,2).map(t=>t.name||t).join(' · ')}</small>}</td><td><div className="author-cell"><span className="author-avatar">{(a.author?.name||'C').charAt(0)}</span>{a.author?.name||'Chemsiq Editorial'}</div></td><td><span className={`status-pill ${a.status==='published'?'published':'draft'}`}><i/>{a.status==='published'?'Published':'Draft'}</span></td><td>{fmt(a.updatedAt||a.createdAt)}</td><td><div className="row-menu"><button title="Edit article" onClick={()=>setEditor(a)}><FileText size={15}/></button><button title="Toggle status" onClick={()=>toggle(a)}>{a.status==='published'?<ArrowDown size={15}/>:<ArrowUp size={15}/>}</button><button title="Delete article" onClick={()=>setDeleteItem(a)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div><footer className="table-footer"><span>Showing <b>{filtered.length?1:0}–{filtered.length}</b> of <b>{filtered.length}</b> articles</span><div><button disabled><ChevronLeft size={16}/></button><button className="page-current">1</button><button disabled><ChevronRight size={16}/></button></div></footer></section><div className="footnote"><Sparkles size={14}/> Thoughtful science, shared simply. <span>Chemsiq Studio</span></div></div></main>
  {editor&&<Editor initial={editor._id||editor.id?editor:null} categories={categories} topics={topics} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);setNotice('Article saved successfully.');load()}}/>}{showBulk&&<Bulk categories={categories} topics={topics} onClose={()=>setShowBulk(false)} onDone={()=>{setNotice('Bulk import finished.');load()}}/>}{deleteItem&&<div className="overlay"><section className="confirm-modal"><div className="danger-icon"><Trash2/></div><h2>Delete this article?</h2><p><b>{deleteItem.title}</b> will be permanently removed from your workspace.</p><footer><button className="secondary" onClick={()=>setDeleteItem(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete article</button></footer></section></div>}{notice&&<div className="toast"><Check size={17}/>{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}</div>
}
function Stat({icon,label,value,note,tone}){return <div className="card stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div className="stat-copy"><small>{label}</small><div><strong>{value}</strong><span className="stat-trend"><ArrowUp size={12}/>—</span></div><p>{note}</p></div><div className="stat-spark">⌁</div></div>}
